import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { gzipSync } from 'node:zlib';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const packLock = JSON.parse(
	readFileSync('document-worker.lock.json', 'utf8'),
);

const inlineDocumentWorkerResources = {
	name: 'inline-document-worker-resources',
	setup(build) {
		build.onResolve(
			{ filter: /^virtual:document-worker-resources$/ },
			() => ({
				path: 'virtual:document-worker-resources',
				namespace: 'document-worker-resources',
			}),
		);

		build.onLoad(
			{
				filter: /.*/,
				namespace: 'document-worker-resources',
			},
			() => {
				const resourceDirectory = path.resolve(
					'.cache',
					'document-worker',
					packLock.documentWorker.commit,
					'resources',
				);
				const entries = packLock.resources.map((resource) => {
					const contents = readFileSync(
						path.join(resourceDirectory, resource.path),
					);
					const sha256 = createHash('sha256')
						.update(contents)
						.digest('hex');
					if (sha256 !== resource.sha256) {
						throw new Error(
							`Resource SHA-256 mismatch during bundle: ${resource.path}`,
						);
					}
					return [
						resource.path,
						gzipSync(contents, { level: 9 }).toString('base64'),
					];
				});
				const manifest = {
					packApiVersion: packLock.packApiVersion,
					packVersion: packLock.packVersion,
					documentWorkerCommit: packLock.documentWorker.commit,
					documentWorkerArchiveSha256:
						packLock.documentWorker.archiveSha256,
					resources: packLock.resources,
				};

				return {
					contents: `
						const resources = new Map(${JSON.stringify(entries)});
						export const enhancementPackManifest = ${JSON.stringify(manifest)};
						export default function resourceContext(path) {
							return resources.get(path);
						}
					`,
					loader: 'js',
				};
			},
		);
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [inlineDocumentWorkerResources],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
