import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { appendFileSync, readFileSync } from 'node:fs';
import { createTrailer, verifyBundle } from './scripts/pack-container.mjs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const appendResourceTrailer = {
	name: 'append-offline-pack-v2',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length) return;
			const lock = JSON.parse(
				readFileSync('document-worker.lock.json', 'utf8'),
			);
			const manifest = JSON.parse(readFileSync('manifest.json', 'utf8'));
			if (lock.packVersion !== manifest.version)
				throw new Error('Pack versions disagree');
			const directory = path.resolve(
				'.cache',
				'document-worker',
				lock.documentWorker.commit,
				'resources',
			);
			const trailer = createTrailer(lock, directory);
			appendFileSync('main.js', trailer);
			if (!prod) verifyBundle(readFileSync('main.js'), lock);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [appendResourceTrailer],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
